{{- if .Values.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    app: {{ template "logginghelm.name" . }}
    chart: {{ template "logginghelm.chart" . }}
    release: {{ .Release.Name }}
    openshift.io/cluster-monitoring: "true"
spec: {}
{{- end }}
