apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicluster-observability-addon-hub-resources
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["perses.dev"]
    resources: ["persesdashboards", "persesdatasources"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["observability.openshift.io"]
    resources: ["uiplugins"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions", "operatorgroups"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-observability-addon-hub-resources
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-observability-addon-hub-resources
subjects:
  - kind: ServiceAccount
    name: multicluster-observability-addon-manager
    namespace: open-cluster-management-observability
