apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-observability-addon-manager
  labels:
    app: multicluster-observability-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-observability-addon-manager
  template:
    metadata:
      labels:
        app: multicluster-observability-addon-manager
    spec:
      serviceAccountName: multicluster-observability-addon-manager
      containers:
        - name: controller
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "controller"
            - "--metrics-bind-address=127.0.0.1:8080"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
        - name: kube-rbac-proxy
          image: quay.io/stolostron/kube-rbac-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --secure-listen-address=0.0.0.0:8444
            - --upstream=http://127.0.0.1:8080
            - --tls-cert-file=/etc/tls/private/tls.crt
            - --tls-private-key-file=/etc/tls/private/tls.key
            - --logtostderr=true
            - --allow-paths=/metrics
          ports:
            - name: https-metrics
              containerPort: 8444
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: metrics-certs
              mountPath: /etc/tls/private
              readOnly: true
      volumes:
        - name: metrics-certs
          secret:
            secretName: multicluster-observability-addon-manager-metrics-certs
            optional: true
