{{- if .Values.DeployNonOCPStack }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-exporter.labels" . | nindent 4 }}
{{- end }}