nameOverride: null

enabled: false
metricsWriteEndpoint: "http://observability-thanos-receive.open-cluster-management-observability.svc.cluster.local:19291"
metricsReadEndpoint: "http://observability-thanos-query-frontend.open-cluster-management-observability.svc.cluster.local:9090"
