{{- if or .Values.platformEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.platform.appName }}-role
  labels:
    app.kubernetes.io/component: platform-metrics-collector
    {{ include "metricshelm.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
      - pods
{{- end }}