{{- if or .Values.platformEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.platformAppName }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.platformAppName }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.platformAppName }}
  namespace: open-cluster-management-addon-observability
{{- end }}