{{- if .Values.platformEnabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: {{ .Values.platform.appName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.prometheus.io/controller-id: {{ .Values.prometheusControllerID }}
  labels:
    {{- $incomingLabels := .Values.platform.prometheusAgent.labels }}
    {{- $metricsHelmLabels := fromYaml (include "metricshelm.labels" $) }}
    {{- $customLabel := dict "app.kubernetes.io/component" $.Values.platform.component }}
    {{- $mergedLabels := merge $incomingLabels $metricsHelmLabels $customLabel }}
    {{- toYaml $mergedLabels | nindent 4 }}
spec:
{{- fromJson .Values.platform.prometheusAgent.data | toYaml | nindent 2 }}
{{- end }}