{{- if .Values.platformEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.platform.appName }}-metrics
  abels:
    app.kubernetes.io/component: {{ .Values.platform.component }}
    app.kubernetes.io/name: {{ .Values.platform.appName }}-metrics
    {{ include "metricshelm.labels" . | nindent 4 }}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
{{- end }}