{{- if or .Values.platformEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.platform.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: platform-metrics-collector
    {{ include "metricshelm.labels" . | nindent 4 }}
{{- end }}