{{- if .Values.enabled }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: monitoring
  labels:
    app: {{ template "incidentDetectionhelm.name" . }}
    chart: {{ template "incidentDetectionhelm.chart" . }}
    release: {{ .Release.Name }}
spec:
  monitoring:
    incidents:
      enabled: true
  type: Monitoring
{{- end }}
