{{- if .Values.enabled }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: monitoring
spec:
  monitoring:
    incidents:
      enabled: true
  type: Monitoring
{{- end }}
