{{- if .Values.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-observability-operator
  labels:
    app: {{ template "incidentDetectionhelm.name" . }}
    chart: {{ template "incidentDetectionhelm.chart" . }}
    release: {{ .Release.Name }}
{{- end }}