{{- if and .Values.rightSizing .Values.rightSizing.scrapeConfig }}
apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ .Values.rightSizing.scrapeConfig.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $incomingLabels := .Values.rightSizing.scrapeConfig.labels }}
    {{- $mcoaHelmLabels := fromYaml (include "mcoahelm.labels" $) }}
    {{- $customLabel := dict "app.kubernetes.io/component" "right-sizing" }}
    {{- $mergedLabels := mergeOverwrite $incomingLabels $mcoaHelmLabels $customLabel }}
    {{- toYaml $mergedLabels | nindent 4 }}
  annotations:
    operator.prometheus.io/controller-id: {{ default "" .Values.metrics.prometheusControllerID }}
spec:
{{ fromJson .Values.rightSizing.scrapeConfig.data | toYaml | nindent 2 }}
{{- end }}
