{{- if eq (include "mcoahelm.installCOO" .) "true" }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator
  labels:
    operators.coreos.com/cluster-observability-operator.openshift-cluster-observability: ''
    app: {{ template "mcoahelm.name" . }}
    chart: {{ template "mcoahelm.chart" . }}
    release: {{ .Release.Name }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
