{{- if .Values.platformEnabled }}
apiVersion: {{ if .Values.deployNonOCPStack }}monitoring.rhobs/v1{{ else }}monitoring.coreos.com/v1{{ end }}
kind: ServiceMonitor
metadata:
  name: {{ .Values.platform.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.platform.component }}
    {{ include "metricshelm.labels" . | nindent 4 }}
spec:
  endpoints:
  {{- if .Values.deployNonOCPStack }}
  - interval: 30s
    port: metrics
    scheme: http
  {{- else }}
  - interval: 30s
    port: metrics
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      serverName: "{{ .Values.platform.appName }}.{{ .Release.Namespace }}.svc"
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.platform.component }}
      app.kubernetes.io/name: {{ .Values.platform.appName }}
{{- end }}
