{{- if .Values.platformEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.platform.appName }}-tls-profile
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.platform.component }}
    app.kubernetes.io/name: {{ .Values.platform.appName }}-tls-profile
    {{ include "metricshelm.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.platform.appName }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.platform.appName }}-tls-profile
{{- end }}
