{{- range $_, $cluster_name := .Values.spokeClusters }}
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: multicluster-observability-addon
  namespace: {{ $cluster_name }}
spec:
  installNamespace: {{ $.Values.addonInstallNamespace }}
  configs:
{{- if $.Values.logging.enabled }}
  # Logging Auth ConfigMap
  - resource: configmaps
    name: logging-auth
    namespace: open-cluster-management
  # Logging URLs for Loki ConfigMap
{{- range $_, $dic := $.Values.logging.outputs }}
{{- if eq $dic.type "loki" }}
  - resource: configmaps
    name: logging-{{ $cluster_name }}-{{ $dic.name }}
    namespace: {{ $cluster_name }}
{{- end }}
{{- end }}
{{- range $_, $dic := $.Values.logging.outputs }}
{{- if eq $dic.type "loki" }}
  # Logging ca-bundle ConfigMap
  - resource: configmaps
    name: lokistack-hub-gateway-ca-bundle
    namespace: openshift-logging
{{- break }}
{{- end }}
{{- end }}
{{- end }}
{{- if $.Values.tracing.enabled }}
  # Tracing Auth ConfigMap
  - resource: configmaps
    name: tracing-auth
    namespace: open-cluster-management
  # Tracing ca-bundle configmap
  - resource: secrets
    name: otel-gateway
    namespace: observability
  # Endpoints for Tracing
{{- range $_, $dic := $.Values.tracing.outputs }}
  - resource: configmaps
    name: tracing-{{ $cluster_name }}-{{ $dic.type }}
    namespace: {{ $cluster_name }}
{{- end }}
{{- end }}
{{- end }}