{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "metricshelm.labels" . | nindent 4 }}
{{- end }}