{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: acm-prometheus-operator
  labels:
    app.kubernetes.io/component: {{ .Values.prometheusOperator.component }}
    app.kubernetes.io/name: {{ .Values.prometheusOperator.appName }}
    {{ include "metricshelm.labels" . | nindent 4 }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
      - prometheuses/finalizers
      - prometheuses/status
      - servicemonitors
      - podmonitors
      - probes
      - prometheusrules
      - prometheuses/status
      - prometheusagents
      - prometheusagents/finalizers
      - prometheusagents/status
      - scrapeconfigs
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - statefulsets
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
  - verbs:
      - list
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - create
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - services
      - services/finalizers
      - endpoints
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
{{- end }}