{{- if .Values.thanosOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        app.kubernetes.io/component: {{ .Values.thanosOperator.component }}
        app.kubernetes.io/name: {{ .Values.thanosOperator.appName }}
        {{ include "metricshelm.labels" . | nindent 8 }}
    name: thanos-operator-thanosruler-viewer-role
rules:
    - apiGroups:
        - monitoring.thanos.io
      resources:
        - thanosrulers
      verbs:
        - get
        - list
        - watch
    - apiGroups:
        - monitoring.thanos.io
      resources:
        - thanosrulers/status
      verbs:
        - get
{{- end }}
