{{- if .Values.thanosOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.thanosOperator.appName }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.thanosOperator.component }}
    app.kubernetes.io/name: {{ .Values.thanosOperator.appName }}
    {{ include "metricshelm.labels" . | nindent 4 }}
{{- if .Values.global.imagePullSecret }}
imagePullSecrets:
  - name: "{{ .Values.global.imagePullSecret }}"
{{- end }}
{{- end }}