{{- if .Values.thanosOperator.enabled }}
{{- $appName := .Values.thanosOperator.appName }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.thanosOperator.component }}
    app.kubernetes.io/name: {{ .Values.thanosOperator.appName }}
    control-plane: controller-manager
    {{ include "metricshelm.labels" . | nindent 4 }}
  name: {{ .Values.thanosOperator.appName }}-controller-manager
  namespace: open-cluster-management-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: {{ .Values.thanosOperator.appName }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: {{ .Values.thanosOperator.appName }}
        app.kubernetes.io/part-of: multicluster-observability-addon
    spec:
      containers:
      - name: kube-rbac-proxy
        image: {{ .Values.images.rbacProxyImage }}
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        {{- if .Values.tlsMinVersion }}
        - --tls-min-version={{ .Values.tlsMinVersion }}
        {{- end }}
        {{- if .Values.tlsCipherSuites }}
        - --tls-cipher-suites={{ .Values.tlsCipherSuites }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /etc/tls/private
          name: tls
          readOnly: true
        resources:
        {{- $matched := false }}
        {{- if .Values.global.resourceRequirements }}
        {{- $reverseResourceRequirements := reverse .Values.global.resourceRequirements -}}
        {{- range $requirement := $reverseResourceRequirements -}}
          {{- if regexMatch $requirement.containerIDRegex (printf "deployments:%s-controller-manager:%s" $appName "kube-rbac-proxy") }}
            {{- $matched = true }}
            {{- toYaml $requirement.resources | nindent 12 }}
            {{- break -}}
          {{- end -}}
        {{- end }}
        {{- end }}
        {{- if not $matched }}
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 10m
            memory: 20Mi
        {{- end }}
      - name: manager
        image: {{ .Values.thanosOperator.image }}
        command:
        - /manager
        args:
        - --leader-elect
        - --metrics-bind-address=127.0.0.1:8080
        - --health-probe-bind-address=:8081
        - --log.format=logfmt
        - --log.level=debug
        - --enable-feature=service-monitor
        - --enable-feature=prometheus-rule
        - --enable-feature=kube-resource-sync
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
        {{- $matched := false }}
        {{- if .Values.global.resourceRequirements }}
        {{- $reverseResourceRequirements := reverse .Values.global.resourceRequirements -}}
        {{- range $requirement := $reverseResourceRequirements -}}
          {{- if regexMatch $requirement.containerIDRegex (printf "deployments:%s-controller-manager:%s" $appName "manager") }}
            {{- $matched = true }}
            {{- toYaml $requirement.resources | nindent 12 }}
            {{- break -}}
          {{- end -}}
        {{- end }}
        {{- end }}
        {{- if not $matched }}
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- else }}
      nodeSelector:
        kubernetes.io/os: linux
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ .Values.thanosOperator.appName }}-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: tls
        secret:
          defaultMode: 420
          secretName: {{ .Values.thanosOperator.appName }}-kube-rbac-proxy-tls
{{- end }}
