{{- if and .Values.thanosOperator.enabled .Values.thanosOperator.storeSpec.data }}
apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosStore
metadata:
  name: mcoa-store
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: store
    app.kubernetes.io/name: {{ .Values.thanosOperator.appName }}
    {{ include "metricshelm.labels" . | nindent 4 }}
spec:
{{- fromJson .Values.thanosOperator.storeSpec.data | toYaml | nindent 2 }}
{{- end }}