{{- if and .Values.thanosOperator.enabled .Values.thanosOperator.rulerSpec.data }}
apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosRuler
metadata:
  name: {{ .Values.thanosOperator.appName }}-ruler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metricshelm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ruler
    app.kubernetes.io/part-of: thanos
spec:
{{- fromJson .Values.thanosOperator.rulerSpec.data | toYaml | nindent 2 }}
{{- end }}