{{- if .Values.userWorkloadsEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.userWorkload.appName }}-rolebinding
  labels:
    app.kubernetes.io/component: user-workload-metrics-collector
    {{ include "metricshelm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.userWorkload.appName }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.userWorkload.appName }}
  namespace: open-cluster-management-addon-observability
{{- end }}