{{- if or .Values.userWorkloadsEnabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: {{ .Values.userWorkloadAppName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.prometheus.io/controller-id: {{ .Values.prometheusControllerID }}
  labels:
    app: {{ .Values.userWorkloadAppName }}
spec:
{{- fromJson .Values.userWorkloadsAgentSpec | toYaml | nindent 2 }}
{{- end }}