{{- if or .Values.userWorkloadsEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.userWorkload.appName }}-cluster-monitoring-view-rolebinding
  labels:
    app.kubernetes.io/component: user-workload-metrics-collector
    {{ include "metricshelm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: {{ .Values.userWorkload.appName }}
  namespace: {{ .Release.Namespace }}
{{- end }}