{{- if or .Values.userWorkloadsEnabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.userWorkloadAppName }}-role
  labels:
    app.kubernetes.io/component: prometheus-agent
    app.kubernetes.io/name: prometheus-agent
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
      - pods
{{- end }}