{{- if .Values.userWorkloadsEnabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: {{ .Values.userWorkload.appName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    operator.prometheus.io/controller-id: {{ .Values.prometheusControllerID }}
  labels:
    app.kubernetes.io/name: {{ .Values.userWorkload.appName }}
    {{- $incomingLabels := .Values.userWorkload.prometheusAgent.labels }}
    {{- $metricsHelmLabels := fromYaml (include "metricshelm.labels" $) }}
    {{- $customLabel := dict "app.kubernetes.io/component" "user-workload-metrics-collector" }}
    {{- $customLabel := dict "app.kubernetes.io/name" .Values.userWorkload.appName }}
    {{- $mergedLabels := merge $incomingLabels $metricsHelmLabels $customLabel }}
    {{- toYaml $mergedLabels | nindent 4 }}
spec:
{{- fromJson .Values.userWorkload.prometheusAgent.data | toYaml | nindent 2 }}
{{- end }}