{{- if .Values.userWorkloadsEnabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.userWorkload.appName }}-metrics
subjects:
  - kind: ServiceAccount
    name: {{ .Values.userWorkload.appName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.userWorkload.appName }}-metrics
{{- end }}