{{- if .Values.userWorkloadsEnabled }}
{{- range $_, $scrapeconfig := .Values.userWorkload.scrapeConfigs }}
apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ $scrapeconfig.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- $incomingLabels := $scrapeconfig.labels }}
    {{- $metricsHelmLabels := fromYaml (include "metricshelm.labels" $) }}
    {{- $customLabel := dict "app.kubernetes.io/component" $.Values.userWorkload.component }}
    {{- if not $.Values.deployCOOResources }}
    {{- $_ := set $customLabel "app.kubernetes.io/managed-by" "observability-operator" }}
    {{- end }}
    {{- $mergedLabels := mergeOverwrite $incomingLabels $metricsHelmLabels $customLabel }}
    {{- toYaml $mergedLabels | nindent 4 }}
  annotations:
    {{- $incomingAnnotations := $scrapeconfig.annotations }}
    {{- $stdAnnotations := dict }}
    {{- if $.Values.deployCOOResources }}
    {{- $_ := set $stdAnnotations "operator.prometheus.io/controller-id" $.Values.prometheusControllerID }}
    {{- else }}
    {{- $_ := set $stdAnnotations "operator.prometheus.io/controller-id" "" }}
    {{- end }}
    {{- $mergedAnnotations := mergeOverwrite $incomingAnnotations $stdAnnotations }}
    {{- toYaml $mergedAnnotations | nindent 4 }}
spec:
{{ fromJson $scrapeconfig.data | toYaml | nindent 2 }}
---
{{- end }}
{{- end }}