{{- if .Values.userWorkloadsEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.userWorkload.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.userWorkload.component }}
    {{ include "metricshelm.labels" . | nindent 4 }}
{{- end }}