{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mcoa.globalResourcePrefix" "endpoint-monitoring-operator" }}
  labels:
    app.kubernetes.io/component: endpoint-monitoring-operator
    {{- include "metricshelm.labels" . | nindent 4 }}
rules:
# Allows updating/patching only the two specific platform configmaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch", "create"]
  resourceNames: ["cluster-monitoring-config"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "update", "patch", "create"]
  resourceNames: ["user-workload-monitoring-config"]
# Namespace-wide "create" needed to initialize them if they don't exist yet
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create"]
# warning events for overwritten/mutated configs
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
{{- end }}
