{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-monitoring-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: endpoint-monitoring-operator
    {{- include "metricshelm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
      app.kubernetes.io/component: endpoint-monitoring-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: endpoint-monitoring-operator
        {{- include "metricshelm.labels" . | nindent 8 }}
    spec:
      serviceAccountName: endpoint-monitoring-operator
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: endpoint-monitoring-operator
        image: {{ .Values.images.endpointMonitoringOperator }}
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/endpoint-monitoring-operator
        args:
        - mcoa
        - --namespace={{ .Release.Namespace }}
        - --metrics-bind-address={{ if .Values.deployNonOCPStack }}0.0.0.0:8080{{ else }}127.0.0.1:8080{{ end }}
        {{- if and .Values.alertManagerEndpoint (or .Values.platformAlertsEnabled .Values.userWorkloadAlertsEnabled) }}
        - --hub-alertmanager-url=https://{{ .Values.alertManagerEndpoint }}/api/alertmanager/v2/default
        - --hub-alertmanager-cert-secret={{ .Values.clientCertSecretName }}
        - --hub-alertmanager-accessor-secret={{ .Values.alertmanagerAccessorSecretName }}
        {{- end }}
        - --hub-alertmanager-ca-secret={{ .Values.alertmanagerRouterCASecretName }}
        - --cluster-id={{ .Values.clusterID }}
        - --cluster-name={{ .Values.clusterName }}
        - --enable-uwl-alert-forwarding={{ and .Values.userWorkloadsEnabled .Values.userWorkloadAlertsEnabled }}
        {{- if .Values.deployNonOCPStack }}
        ports:
        - name: metrics
          containerPort: 8080
        {{- end }}
        resources:
          requests:
            cpu: 1m
            memory: 31Mi
          limits:
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
      {{- if not .Values.deployNonOCPStack }}
      - name: kube-rbac-proxy
        image: {{ .Values.images.rbacProxyImage }}
        imagePullPolicy: IfNotPresent
        args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --logtostderr=true
        - --allow-paths=/metrics
        ports:
        - name: metrics
          containerPort: 8443
        resources:
          requests:
            cpu: 1m
            memory: 15Mi
          limits:
            cpu: 20m
            memory: 30Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: kube-rbac-proxy-tls
          mountPath: /etc/tls/private
          readOnly: true
      {{- end }}
      {{- if not .Values.deployNonOCPStack }}
      volumes:
      - name: kube-rbac-proxy-tls
        secret:
          secretName: endpoint-monitoring-operator-tls
      {{- end }}
{{- end }}
