{{- if and (or .Values.platformEnabled .Values.userWorkloadsEnabled) (not .Values.deployNonOCPStack) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mcoa.globalResourcePrefix" "endpoint-monitoring-operator-metrics" }}
  labels:
    app.kubernetes.io/component: endpoint-monitoring-operator
    {{- include "metricshelm.labels" . | nindent 4 }}
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
{{- end }}
