{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoint-monitoring-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: endpoint-monitoring-operator
    {{- include "metricshelm.labels" . | nindent 4 }}
{{- if .Values.global.imagePullSecret }}
imagePullSecrets:
  - name: "{{ .Values.global.imagePullSecret }}"
{{- end }}
{{- end }}
