{{- if  .Values.deployCOOResources }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheusOperator.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.prometheusOperator.component }}
    app.kubernetes.io/name: {{ .Values.prometheusOperator.appName }}
    {{ include "metricshelm.labels" . | nindent 4 }}
{{- end }}