apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-default
  namespace: open-cluster-management-observability
type: Opaque
data:
  aws_access_key_id: {{ .Values.awsCredentials.accessKeyID | b64enc }}
  aws_secret_access_key: {{ .Values.awsCredentials.accessKeySecret | b64enc }}
