apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance-default
  namespace: open-cluster-management-observability
spec:
  managementState: Unmanaged
  serviceAccount: 
    name: mcoa-logcollector
  outputs:
   - cloudwatch:
       region: eu-central-1
       groupName: mcoa-logs
       authentication:
          type: awsAccessKey
          awsAccessKey:
            keyId:
              secretName: aws-credentials
              key: aws_access_key_id
            keySecret:
              secretName: aws-credentials
              key: aws_secret_access_key
     type: cloudwatch
     name: cw
  pipelines:
   - name: infra-cw
     inputRefs:
     - infrastructure
     outputRefs:
     - cw
