apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instance
  namespace: open-cluster-management-observability
spec:
  exporter:
    endpoint: http://mcoa-instance-collector.mcoa-opentelemetry.svc.cluster.local:4318
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  propagators:
    - jaeger
    - b3
  python:
    env:
      - name: OTEL_LOG_LEVEL
        value: "debug"
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: none

