{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "metricshelm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
{{- end }}