{{- if or .Values.platformEnabled .Values.userWorkloadsEnabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- if ne .Release.Namespace "open-cluster-management-agent-addon" }}
    {{ include "metricshelm.labels" . | nindent 4 }}
    # This label tells the addonsecretcontroller to copy the open-cluster-management-image-pull-credentials
    # pull request secret to the namespace on the mgd cluster
    addon.open-cluster-management.io/namespace: "true"
    {{- end }}
    openshift.io/cluster-monitoring: "true"
{{- end }}
