{{- if .Values.DeployNonOCPStack }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    update-namespace: "false"
  name: {{ include "prometheus.serviceAccountName" . }}
  namespace: default
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "prometheus.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}



{{- end }}