{{- if .Values.DeployNonOCPStack }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    update-namespace: "false"
  name: {{ include "prometheus.serviceAccountName" . }}
  namespace: default
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
{{- end }}