{{- if .Values.deployNonOCPStack }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheusServerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}

{{- end }}