{{- if .Values.deployNonOCPStack }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheusServerName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 9091
    targetPort: https
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
{{- end }}