name: addon build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      id: go
    - name: Install make
      run: sudo apt-get install make
    - name: make addon
      run: |
        make addon
