name: integration 

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: "**/*.sum"

      - name: Install deps
        run: make deps
      - name: Build # Check if the project compiles
        run: make addon

      - name: Run tests
        run: |
          source <(make integration-env)
          make integration-test
