{{- if .Values.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-observability-operator
  labels:
    app: {{ template "observability-operatorhelm.name" . }}
    chart: {{ template "observability-operatorhelm.chart" . }}
    release: {{ .Release.Name }}
---
{{- end }}